name: barbararebolledo
favicon: null
layout_spectrum: 0.1406136837322265
typography_spectrum: 0.770437836414203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7570030095521361
  lightness: 0.5676018777303398
  saturation: 0.2613689820282161
  rhythmicContrast: 0.8364919100422412
purpose: []
